import Link from "next/link";
import { Header, Footer } from "../../components/shell";
import { Icon } from "../../components/icon";
const free = ["All 12 current CV and letter templates", "Guided editing and live previews", "A4 / Letter and print-to-PDF", "Editable backups and browser drafts", "Private cloud documents with a free account", "Writing guides and the Support centre"];
export default function Pricing() {
  return <><Header/><main id="main" className="container service-page pricing-page">
    <div className="page-heading"><span className="eyebrow">FREE & PREMIUM</span><h1>Start with possibility.<br/><em>Choose what’s next.</em></h1><p>Build a document you can be proud of. The essentials are free, with no card required.</p></div>
    <div className="plan-grid"><article className="plan-card"><span className="plan-kicker">READY TODAY</span><h2>Free</h2><div className="plan-price">$0<span>No subscription</span></div><p>Everything you need to create, edit, and save your current application documents.</p><Link className="button full" href="/signup">Create a free account <Icon name="arrow" size={17}/></Link><Link href="/builder" className="plan-secondary">Or try the builder without an account</Link><ul>{free.map(text=><li key={text}><Icon name="check" size={17}/>{text}</li>)}</ul></article>
    <article className="plan-card premium-card"><span className="plan-kicker">IN PLANNING</span><h2>Premium <Icon name="sparkles" size={25}/></h2><div className="plan-price plan-coming">Help shape what’s next</div><p>We’re exploring more ways to support your applications. Tell us which additions would matter to you.</p><Link className="button full" href="/contact?category=premium">Register interest <Icon name="arrow" size={17}/></Link><span className="plan-secondary">No payment · No subscription · No commitment</span><h3>Ideas under consideration</h3><ul><li><Icon name="plus" size={17}/>Expanded layouts and design controls</li><li><Icon name="plus" size={17}/>More ways to organise applications</li><li><Icon name="plus" size={17}/>Additional document review tools</li></ul><p className="premium-disclosure">These are planned ideas, not included features. Pricing and availability have not been announced. Registering interest does not upgrade your account.</p></article></div>
    <section className="plan-comparison"><div><span className="eyebrow">CLEAR FROM THE START</span><h2>What you can use today.</h2></div><div className="table-scroll"><table><caption className="sr-only">Current Free features and Premium availability</caption><thead><tr><th scope="col">Feature</th><th scope="col">Free</th><th scope="col">Premium</th></tr></thead><tbody>{["12 CV and letter templates","PDF printing and JSON backups","Account document storage","Writing guides and support requests"].map(x=><tr key={x}><th scope="row">{x}</th><td>Included</td><td>Not launched</td></tr>)}<tr><th scope="row">Payment required</th><td>No</td><td>No checkout available</td></tr></tbody></table></div></section>
    <div className="service-bottom"><Icon name="shield" size={30}/><div><h2>Your existing work stays available.</h2><p>The current templates and editor remain free. Premium interest is optional, and your documents are not attached to your request.</p></div><Link href="/support" className="button secondary">Questions? Get help</Link></div>
  </main><Footer/></>;
}
